---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: yes
  become_method: sudo
  become_user: root  
  gather_facts: no
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: Wait 60 seconds, but only start checking after 15 seconds
      wait_for_connection:
        delay: 15
        timeout: 60

  roles:
    - deploy