---
- name: "install pm2"
  become: yes
  shell: |
    npm install pm2 -g

- name: "Export env"
  become: yes
  shell:  |
    echo export TYPEORM_HOST=$TYPTYPEORM_HOST >> .profile
    echo export TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> .profile
    echo export TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> .profile
    echo export TYPEORM_HOST=$TYPEORM_HOST >> .profile
    echo export TYPEORM_PORT=$TYPEORM_PORT >> .profile
    echo export TYPEORM_USERNAME=$TYPEORM_USERNAME >> .profile
    echo export TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .profile
    echo export TYPEORM_DATABASE=$TYPEORM_DATABASE >> .profile
    echo export TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> .profile
    echo export TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> .profile
    . ~/.profile