- name: "Create deploy directory"
  file:
    path: "~/webapp"
    state: "directory"
    mode: 0755

- name: "Create logs directory"
  file:
    path: "~/logs"
    state: "directory"
    mode: 0755
  
- name: "copy backend artifact zip file to server"
  copy:
    src: "artifact.tar.gz"
    dest: "~/"

- name: "Unzip backend artifact"
  unarchive:
    remote_src: yes
    src: "~/artifact.tar.gz"
    dest: "~/webapp"

- name: "start backend server"
  shell: |
    cd webapp
    pm2 stop default
    pm2 start npm --name "udapeople" -- start