- name: "Create deploy directory"
  file:
    path: "~/webapp"
    state: "directory"
    mode: 0755
  
- name: "copy backend artifact zip file to server"
  copy:
    src: "artifact-backend.tar.gz"
    dest: "~/webapp"

- name: "Unzip backend artifact"
  unarchive:
    remote_src: yes
    src: "~/webapp/artifact-backend.tar.gz"
    dest: "~/webapp"

- name: "start backend server"
  shell:
    cmd: |
    cd ~/webapp
    pm2 stop default
    pm2 start npm -- start --wait-ready